name: Battle Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: [ "battle/**" ]

env:
  DOCKER_IMAGE_BATTLE: "djheadset/pokemon_battle:latest"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Users build and push
        uses: docker/build-push-action@v5
        with:
          context: ./users
          push: true
          tags: ${{ env.DOCKER_IMAGE_BATTLE }}